### ISSUE TITLE
Error while using Spark Package CMD Tools - ImportError: No module named requests

### ISSUE THREAD

**Issue by samuelalexanderg** [databricks/spark-package-cmd-tool#2]
I am trying to using Spark Package CMD Tools.

I installed it using pip install spark-package. I am having ubunt 12.04. 

Here is my python version

sam@sam:~$ python --version
Python 2.7.3

And here is the exception that I am getting when I try to using CMD Tools

sam@sam:~$ spark-package init
Traceback (most recent call last):
  File "/usr/local/bin/spark-package", line 9, in <module>
    load_entry_point('spark-package==0.3.1', 'console_scripts', 'spark-package')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/spark_package/spark_package.py", line 21, in <module>
    import requests
ImportError: No module named requests

Am I missing any python modules here?

**Comment by brkyvz** [comment]
Hi,
Could you also use `$ pip install requests`? In addition, you have to add the name of the package you would like to create to `spark-package init`. For example:
`spark-package init -n "my/package"` will create a Spark Package template with scala code with the name `my/package`. Then you will need a GitHub repo with the name `my/package`. 

In order to add python, scala or java directories, please use `-p`, `-s`, and `-j`.

Best,
Burak

**Comment by samuelalexanderg** [comment]
Thanks Burak,

$ pip install requests solved the issue. I did spark-package init -n "my_org/my_package" -s and able to see the packages created.

Thanks,
Sam.
